### ISSUE TITLE
Appimage, please.

### ISSUE THREAD

**Issue by abdullahezzat1** [Jessewb786/Silaty#13]
I'm using red hat enterprise linux 8. It doesn't have any of the dependencies, and snap is too heavy to use.

It would be great to have an appimage version of this.

Thanks.

**Comment by AXeL-dev** [comment]
What about the [snap](https://snapcraft.io/silaty) package, have you tried it?

**Comment by abdullahezzat1** [comment]
Yes, I tried it. It was working and it crashes after updating.

I try to avoid using snaps in general because they are heavier than original packages.

**Comment by AXeL-dev** [comment]
Okay, i'll try to find some time to setup & test the AppImage. @xlmnxp may i ask you for some help :pray: ?

**Edit**: @abdullahezzat1 this may take some time since i'm busy those days, have you try manual installation? Find below the list of dependencies that you might need to install manually.

https://github.com/LinuxForGeeks/Silaty/blob/228968a478e223b043a83897105297834965b7a7/debian/control#L10

**Comment by AXeL-dev** [comment]
@abdullahezzat1 Can you try the following AppImage [Silaty-1.4-x86_64.AppImage](https://github.com/LinuxForGeeks/Silaty/releases/download/v1.4/Silaty-1.4-x86_64.AppImage).

**Comment by xlmnxp** [comment]
> Okay, i'll try to find some time to setup & test the AppImage. @xlmnxp may i ask you for some help 🙏 ?
> 
> **Edit**: @abdullahezzat1 this may take some time since i'm busy those days, have you try manual installation? Find below the list of dependencies that you might need to install manually.
> 
> https://github.com/LinuxForGeeks/Silaty/blob/228968a478e223b043a83897105297834965b7a7/debian/control#L10

Snapcraft sent security alert and asked me to "trigger new build" 
I did that but application cannot work, I searched few weeks to found what is the issue but I couldn't

**Comment by AXeL-dev** [comment]
> Snapcraft sent security alert and asked me to "trigger new build"
> I did that but application cannot work, I searched few weeks to found what is the issue but I couldn't

When did you receive the security alert? & what was the content/purpose of the security alert? is it a vulnerable dependency or something else?

**Comment by abdullahezzat1** [comment]
I got this error:

Traceback (most recent call last):
  File "/tmp/.mount_SilatyfYzw1Y///usr/local/bin/silaty-indicator", line 13, in <module>
    gi.require_version('Gtk', '3.0')
  File "/tmp/.mount_SilatyfYzw1Y/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

**Comment by AXeL-dev** [comment]
> I got this error:
> 
> Traceback (most recent call last):
> File "/tmp/.mount_SilatyfYzw1Y///usr/local/bin/silaty-indicator", line 13, in
> gi.require_version('Gtk', '3.0')
> File "/tmp/.mount_SilatyfYzw1Y/usr/lib/python3/dist-packages/gi/**init**.py", line 130, in require_version
> raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Gtk not available

:thinking: what is your distro? can you remind me please? i guess Redhat, but i need to know the exact release number.

**Comment by abdullahezzat1** [comment]
Oracle Linux 8.3 (redhat compatible)

**Comment by AXeL-dev** [comment]
> I got this error:
> 
> Traceback (most recent call last):
> File "/tmp/.mount_SilatyfYzw1Y///usr/local/bin/silaty-indicator", line 13, in
> gi.require_version('Gtk', '3.0')
> File "/tmp/.mount_SilatyfYzw1Y/usr/lib/python3/dist-packages/gi/**init**.py", line 130, in require_version
> raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Gtk not available

Okay, i just tried on a VM & got a similar issue:

![image](https://user-images.githubusercontent.com/30635693/110211477-03921980-7e97-11eb-8d57-ffd04b524dbf.png)

Both issues seems to be related to missing dependencies, so i guess that i'll have to rebuild the AppImage on a new machine & see if i can fix the dependencies issues (but this will have to wait for later, i spent the last night working on this & i prefer to take a break now, sorry :pray:).

You can still try to do a [manual installation](https://github.com/Jessewb786/Silaty#install-from-source) after manually installing the dependencies, below the dependencies list (from both snap & appimage configs):

https://github.com/LinuxForGeeks/Silaty/blob/5a4dc138752c8cd6ce85657ed85b511bb27acaa8/snap/snapcraft.yaml#L19-L32

https://github.com/LinuxForGeeks/Silaty/blob/5a4dc138752c8cd6ce85657ed85b511bb27acaa8/AppImageBuilder.yml#L38-L59

**Comment by abdullahezzat1** [comment]
I'll give it a try.

**Comment by xlmnxp** [comment]
> > Snapcraft sent security alert and asked me to "trigger new build"
> > I did that but application cannot work, I searched few weeks to found what is the issue but I couldn't
> 
> When did you receive the security alert? & what was the content/purpose of the security alert? is it a vulnerable dependency or something else?

I got 2
first on 19/02/2021
```
A scan of this snap shows that it was built with packages from the Ubuntu
archive that have since received security updates. The following lists new
USNs for affected binary packages in each snap revision:

Revision r6 (armhf; channels: stable, candidate, beta, edge)
 * libssl1.1: 4738-1

Revision r7 (amd64; channels: stable, candidate, beta, edge)
 * libssl1.1: 4738-1

Revision r8 (i386; channels: stable, candidate, beta, edge)
 * libssl1.1: 4738-1

Revision r9 (arm64; channels: stable, candidate, beta, edge)
 * libssl1.1: 4738-1

Simply rebuilding the snap will pull in the new security updates and
resolve this. If your snap also contains vendored code, now might be a
good time to review it for any needed updates.

Thank you for your snap and for attending to this matter.

References:
 * https://ubuntu.com/security/notices/USN-4738-1/
 ```

second on 26/02/21
```
A scan of this snap shows that it was built with packages from the Ubuntu
archive that have since received security updates. The following lists new
USNs for affected binary packages in each snap revision:

Revision r6 (armhf; channels: stable, candidate, beta, edge)
 * libpython3.6-minimal: 4754-1
 * libpython3.6-stdlib: 4754-1
 * libtiff5: 4755-1
 * python3.6: 4754-1
 * python3.6-minimal: 4754-1

Revision r7 (amd64; channels: stable, candidate, beta, edge)
 * libpython3.6-minimal: 4754-1
 * libpython3.6-stdlib: 4754-1
 * libtiff5: 4755-1
 * python3.6: 4754-1
 * python3.6-minimal: 4754-1

Revision r8 (i386; channels: stable, candidate, beta, edge)
 * libpython3.6-minimal: 4754-1
 * libpython3.6-stdlib: 4754-1
 * libtiff5: 4755-1
 * python3.6: 4754-1
 * python3.6-minimal: 4754-1

Revision r9 (arm64; channels: stable, candidate, beta, edge)
 * libpython3.6-minimal: 4754-1
 * libpython3.6-stdlib: 4754-1
 * libtiff5: 4755-1
 * python3.6: 4754-1
 * python3.6-minimal: 4754-1

Simply rebuilding the snap will pull in the new security updates and
resolve this. If your snap also contains vendored code, now might be a
good time to review it for any needed updates.

Thank you for your snap and for attending to this matter.

References:
 * https://ubuntu.com/security/notices/USN-4754-1/
 * https://ubuntu.com/security/notices/USN-4755-1/
```

**Comment by AXeL-dev** [comment]
Thanks @xlmnxp, i'll try to look at this once i get some time, i'm also thinking to add a [Flathub](https://flathub.org) package :bulb:.
